using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace BlackGoldAncientSword.Framework.SourceGenerator
{
    [Generator]
    internal class EnumSourceGenerator : IIncrementalGenerator
    {
        private static readonly JsonSerializerOptions JsonOptions = new()
        {
            PropertyNameCaseInsensitive = true,
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase
        };

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var enumFiles = context.AdditionalTextsProvider
                .Where(static file =>
                    file.Path.EndsWith("enums.json", StringComparison.OrdinalIgnoreCase))
                .Select(static (file, ct) =>
                {
                    var sourceText = file.GetText(ct);
                    return sourceText?.ToString() ?? string.Empty;
                })
                .Where(static text => !string.IsNullOrWhiteSpace(text));

            context.RegisterSourceOutput(enumFiles, GenerateAllEnums);
        }

        private void GenerateAllEnums(SourceProductionContext context, string json)
        {
            try
            {
                var root = JsonSerializer.Deserialize<EnumDefinitionsRoot>(json, JsonOptions);
                if (root == null || root.Enums.Count == 0) return;

                foreach (var enumDef in root.Enums)
                    GenerateEnumFile(context, enumDef);

                if (root.HelperMethods != null)
                    GenerateHelperMethods(context, root.Enums, root.HelperMethods);
            }
            catch (Exception ex)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor("ENUMGEN001", "Enum Generator Error",
                        $"Failed to generate enum code: {ex.Message}",
                        "EnumSourceGenerator", DiagnosticSeverity.Error, isEnabledByDefault: true),
                    Location.None));
            }
        }

        private void GenerateEnumFile(SourceProductionContext context, EnumDefinition def)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System.ComponentModel;");
            sb.AppendLine();
            sb.AppendLine($"namespace {def.Namespace}");
            sb.AppendLine("{");

            if (!string.IsNullOrEmpty(def.Description))
            {
                sb.AppendLine($"    /// <summary>");
                sb.AppendLine($"    /// {def.Description}");
                sb.AppendLine($"    /// </summary>");
            }

            var underlying = def.UnderlyingType ?? "int";
            sb.AppendLine($"    public enum {def.Name} : {CSharpType(underlying)}");
            sb.AppendLine("    {");

            for (int i = 0; i < def.Values.Count; i++)
            {
                var val = def.Values[i];
                var isLast = i == def.Values.Count - 1;
                sb.AppendLine($"        /// <summary>");
                sb.AppendLine($"        /// {val.Description}");
                sb.AppendLine($"        /// </summary>");
                sb.AppendLine($"        [Description(\"{val.Description}\")]");
                sb.Append($"        {val.Name} = {EnumValueLiteral(val.GetValueString(), underlying)}");
                sb.AppendLine(isLast ? "" : ",");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource($"{def.Name}.Generated.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private void GenerateHelperMethods(SourceProductionContext context,
            List<EnumDefinition> enums, Dictionary<string, List<HelperMethodDefinition>> helperMethods)
        {
            var targetNs = enums.Select(e => e.Namespace).FirstOrDefault()
                ?? "BlackGoldAncientSword.Framework.Core.Consts";
            var enumLookup = enums.ToDictionary(e => e.Name);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.ComponentModel;");
            sb.AppendLine();
            sb.AppendLine($"namespace {targetNs}");
            sb.AppendLine("{");

            foreach (var kvp in helperMethods)
            {
                var enumName = kvp.Key; var methods = kvp.Value;
                if (!enumLookup.ContainsKey(enumName)) continue;

                sb.AppendLine($"    /// <summary>");
                sb.AppendLine($"    /// {enumName} 枚举的扩展方法");
                sb.AppendLine($"    /// </summary>");
                sb.AppendLine($"    public static partial class {enumName}Extensions");
                sb.AppendLine("    {");

                foreach (var method in methods)
                {
                    var returnTypeCs = method.ReturnType ?? "void";

                    // === XML doc ===
                    sb.AppendLine($"        /// <summary>");
                    sb.AppendLine($"        /// {method.Description}");
                    sb.AppendLine($"        /// </summary>");

                    // Extension method: <param name="value">
                    if (!method.IsStatic)
                        sb.AppendLine($"        /// <param name=\"value\">当前 {enumName} 枚举值</param>");

                    // Parameters
                    if (method.Parameters != null)
                    {
                        foreach (var p in method.Parameters)
                        {
                            var paramDesc = !string.IsNullOrEmpty(p.Description)
                                ? p.Description
                                : $"参数 {p.Name}";
                            sb.AppendLine($"        /// <param name=\"{p.Name}\">{paramDesc}</param>");
                        }
                    }

                    // Returns
                    if (!string.IsNullOrEmpty(method.Returns))
                        sb.AppendLine($"        /// <returns>{method.Returns}</returns>");

                    // === Method signature ===
                    var paramList = method.IsStatic
                        ? string.Join(", ", method.Parameters?.Select(p => $"{p.Type} {p.Name}")
                            ?? Array.Empty<string>())
                        : $"this {enumName} value"
                            + (method.Parameters != null && method.Parameters.Count > 0
                                ? ", " + string.Join(", ", method.Parameters.Select(p => $"{p.Type} {p.Name}"))
                                : "");

                    sb.AppendLine($"        public static {returnTypeCs} {method.Name}({paramList})");
                    sb.AppendLine("        {");

                    if (!string.IsNullOrEmpty(method.Body))
                    {
                        var body = method.IsStatic ? method.Body : method.Body.Replace("this", "value");
                        foreach (var line in body.Split('\n'))
                            sb.AppendLine($"            {line.Trim()}");
                    }

                    sb.AppendLine("        }");
                    sb.AppendLine();
                }

                sb.AppendLine("    }");
            }

            sb.AppendLine("}");
            context.AddSource("EnumExtensions.Generated.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private static string CSharpType(string type) => type switch
        {
            "string" => "string",
            "int" => "int",
            "long" => "long",
            "byte" => "byte",
            _ => "int"
        };

        private static string EnumValueLiteral(string value, string underlyingType) => underlyingType switch
        {
            "string" => $"\"{value}\"",
            _ => value
        };

        // ======== JSON Model ========

        private class EnumDefinitionsRoot
        {
            public List<EnumDefinition> Enums { get; set; } = new();
            public Dictionary<string, List<HelperMethodDefinition>> HelperMethods { get; set; } = new();
        }

        private class EnumDefinition
        {
            public string Name { get; set; } = string.Empty;
            public string Namespace { get; set; } = string.Empty;
            public string Description { get; set; } = string.Empty;
            public string UnderlyingType { get; set; } = "int";
            public List<EnumValueDefinition> Values { get; set; } = new();
        }

        private class EnumValueDefinition
        {
            public string Name { get; set; } = string.Empty;
            public System.Text.Json.JsonElement Value { get; set; }
            public string Description { get; set; } = string.Empty;

            public string GetValueString()
            {
                return Value.ValueKind == JsonValueKind.Number ? Value.GetRawText() : Value.GetString() ?? string.Empty;
            }
        }

        private class HelperMethodDefinition
        {
            public string Name { get; set; } = string.Empty;
            public bool IsStatic { get; set; }
            public string ReturnType { get; set; } = "void";
            public string Description { get; set; } = string.Empty;
            public string Returns { get; set; } = string.Empty;
            public string Body { get; set; } = string.Empty;
            public List<MethodParameterDefinition> Parameters { get; set; } = new();
        }

        private class MethodParameterDefinition
        {
            public string Name { get; set; } = string.Empty;
            public string Type { get; set; } = string.Empty;
            public string Description { get; set; } = string.Empty;
        }
    }
}