using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

namespace BlackGoldAncientSword.Framework.SourceGenerator
{
    [Generator]
    internal class HttpApiSourceGenerator : IIncrementalGenerator
    {
        private static readonly JsonSerializerOptions JsonOptions = new()
        {
            PropertyNameCaseInsensitive = true,
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase
        };

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Read RootNamespace from MSBuild, e.g. "BlackGoldAncientSword.Framework"
            var rootNsProvider = context.AnalyzerConfigOptionsProvider
                .Select(static (options, _) =>
                    options.GlobalOptions.TryGetValue("build_property.RootNamespace", out var ns)
                        ? ns
                        : "RootNamespace");

            var jsonFiles = context.AdditionalTextsProvider
                .Where(static file =>
                    file.Path.EndsWith(".json", StringComparison.OrdinalIgnoreCase) &&
                    file.Path.Contains("Definitions"))
                .Select(static (file, ct) =>
                {
                    var sourceText = file.GetText(ct);
                    return sourceText?.ToString() ?? string.Empty;
                })
                .Where(static text => !string.IsNullOrWhiteSpace(text));

            var combined = jsonFiles.Combine(rootNsProvider);

            context.RegisterSourceOutput(combined, GenerateAllSources);
        }

        private void GenerateAllSources(SourceProductionContext context, (string json, string rootNs) input)
        {
            var (json, rootNs) = input;
            var httpNs = $"{rootNs}.Http";
            var generatedNs = $"{httpNs}.Generated";

            try
            {
                var root = JsonSerializer.Deserialize<ApiDefinitionsRoot>(json, JsonOptions);
                if (root == null || root.Apis.Count == 0) return;

                GenerateDtos(context, root, generatedNs);
                GenerateStaticClient(context, root, httpNs, generatedNs);
            }
            catch (Exception ex)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor("HTTPGEN001", "HTTP API Generator Error",
                        $"Failed to generate HTTP API code: {ex.Message}",
                        "HttpApiSourceGenerator", DiagnosticSeverity.Error, isEnabledByDefault: true),
                    Location.None));
            }
        }

        // ==================== DTOs ====================

        private void GenerateDtos(SourceProductionContext context, ApiDefinitionsRoot root, string ns)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>API response interface for extracting error messages</summary>");
            sb.AppendLine("    public interface IApiResponse");
            sb.AppendLine("    {");
            sb.AppendLine("        int Code { get; }");
            sb.AppendLine("        string Msg { get; }");
            sb.AppendLine("    }");
            sb.AppendLine();

            var allTypes = new HashSet<string>();
            foreach (var api in root.Apis)
            {
                if (api.RequestBody != null)
                    GenerateType(sb, api.RequestBody, allTypes, "    ");
                if (api.ResponseBody != null)
                    GenerateTypeWithNested(sb, api.ResponseBody, allTypes, "    ");
            }

            sb.AppendLine("}");
            context.AddSource("HttpDtos.Generated.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        // ==================== Static Client ====================

        private void GenerateStaticClient(SourceProductionContext context, ApiDefinitionsRoot root, string httpNs, string generatedNs)
        {
            var sb = new StringBuilder();
            var enumTypeNames = new HashSet<string>(root.EnumTypeNames ?? new List<string>());

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using System.Net.Http;");
            sb.AppendLine("using System.Net.Http.Json;");
            sb.AppendLine("using System.Text;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using Newtonsoft.Json;");
            sb.AppendLine($"using {generatedNs};");
            if (enumTypeNames.Count > 0)
                sb.AppendLine("using BlackGoldAncientSword.Framework.Core.Consts;");
            sb.AppendLine();
            sb.AppendLine($"namespace {httpNs}");
            sb.AppendLine("{");
            sb.AppendLine("    public static class NarakaApiClient");
            sb.AppendLine("    {");
            sb.AppendLine($"        private static readonly HttpClient _http = new()");
            sb.AppendLine("        {");
            sb.AppendLine($"            BaseAddress = new Uri(\"{root.BaseUrl}\"),");
            sb.AppendLine("        };");
            sb.AppendLine();
            sb.AppendLine("        static NarakaApiClient()");
            sb.AppendLine("        {");
            foreach (var h in root.DefaultHeaders)
                sb.AppendLine($"            _http.DefaultRequestHeaders.TryAddWithoutValidation(\"{h.Key}\", \"{h.Value}\");");
            sb.AppendLine("        }");
            sb.AppendLine();

            foreach (var api in root.Apis)
                GenerateApiMethod(sb, api, enumTypeNames);

            sb.AppendLine("        #region Internal");
            sb.AppendLine();
            sb.AppendLine("        private static async Task<T> GetAsync<T>(string url, CancellationToken ct)");
            sb.AppendLine("        {");
            sb.AppendLine("            var r = await _http.GetAsync(url, ct);");
            sb.AppendLine("            return await ReadApiResponseAsync<T>(r, ct);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static async Task<TRes> PostAsync<TReq, TRes>(string url, TReq body, CancellationToken ct)");
            sb.AppendLine("        {");
            sb.AppendLine("            var r = await _http.PostAsJsonAsync(url, body, ct);");
            sb.AppendLine("            return await ReadApiResponseAsync<TRes>(r, ct);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static async Task PostVoidAsync<TReq>(string url, TReq body, CancellationToken ct)");
            sb.AppendLine("        {");
            sb.AppendLine("            var r = await _http.PostAsJsonAsync(url, body, ct);");
            sb.AppendLine("            r.EnsureSuccessStatusCode();");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static async Task<TRes> PutAsync<TReq, TRes>(string url, TReq body, CancellationToken ct)");
            sb.AppendLine("        {");
            sb.AppendLine("            var r = await _http.PutAsJsonAsync(url, body, ct);");
            sb.AppendLine("            return await ReadApiResponseAsync<TRes>(r, ct);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static async Task PutVoidAsync<TReq>(string url, TReq body, CancellationToken ct)");
            sb.AppendLine("        {");
            sb.AppendLine("            var r = await _http.PutAsJsonAsync(url, body, ct);");
            sb.AppendLine("            r.EnsureSuccessStatusCode();");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static async Task<T> DeleteAsync<T>(string url, CancellationToken ct)");
            sb.AppendLine("        {");
            sb.AppendLine("            var r = await _http.DeleteAsync(url, ct);");
            sb.AppendLine("            return await ReadApiResponseAsync<T>(r, ct);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static async Task DeleteVoidAsync(string url, CancellationToken ct)");
            sb.AppendLine("        {");
            sb.AppendLine("            var r = await _http.DeleteAsync(url, ct);");
            sb.AppendLine("            r.EnsureSuccessStatusCode();");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static async Task<TRes> PatchAsync<TReq, TRes>(string url, TReq body, CancellationToken ct)");
            sb.AppendLine("        {");
            sb.AppendLine("            var c = new StringContent(JsonConvert.SerializeObject(body), Encoding.UTF8, \"application/json\");");
            sb.AppendLine("            var r = await _http.PatchAsync(url, c, ct);");
            sb.AppendLine("            return await ReadApiResponseAsync<TRes>(r, ct);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static async Task<T> ReadApiResponseAsync<T>(HttpResponseMessage r, CancellationToken ct)");
            sb.AppendLine("        {");
            sb.AppendLine("            var body = await r.Content.ReadAsStringAsync(ct);");
            sb.AppendLine("            if (!r.IsSuccessStatusCode)");
            sb.AppendLine("            {");
            sb.AppendLine("                var apiMsg = TryExtractApiError(body);");
            sb.AppendLine("                throw new HttpRequestException(apiMsg ?? $\"HTTP {(int)r.StatusCode}: {body}\");");
            sb.AppendLine("            }");
            sb.AppendLine("            var result = JsonConvert.DeserializeObject<T>(body)!;");
            sb.AppendLine("            if (result is IApiResponse apiResp && apiResp.Code != 200)");
            sb.AppendLine("                throw new InvalidOperationException(apiResp.Msg ?? $\"API returned code {apiResp.Code}\");");
            sb.AppendLine("            return result;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static string? TryExtractApiError(string body)");
            sb.AppendLine("        {");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine("                var err = JsonConvert.DeserializeAnonymousType(body, new { msg = \"\" });");
            sb.AppendLine("                return !string.IsNullOrEmpty(err?.msg) ? err.msg : null;");
            sb.AppendLine("            }");
            sb.AppendLine("            catch { return null; }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static string BuildQuery(Dictionary<string, string?> p)");
            sb.AppendLine("        {");
            sb.AppendLine("            var q = string.Join(\"&\", p.Where(x => x.Value != null)");
            sb.AppendLine("                .Select(x => $\"{Uri.EscapeDataString(x.Key)}={Uri.EscapeDataString(x.Value!)}\"));");
            sb.AppendLine("            return string.IsNullOrEmpty(q) ? \"\" : \"?\" + q;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        #endregion");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource("NarakaApiClient.Generated.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private void GenerateApiMethod(StringBuilder sb, ApiEndpointDefinition api, HashSet<string> enumTypeNames)
        {
            var methodName = $"{api.Id}Async";
            var method = api.Method.ToUpperInvariant();
            var hasBody = api.RequestBody != null;
            var reqType = hasBody ? $"{api.RequestBody!.Type}" : null;
            var resType = api.ResponseBody != null ? $"{api.ResponseBody!.Type}" : null;
            var returnType = resType != null ? $"Task<{resType}>" : "Task";

            var parameters = new List<string>();
            if (api.PathParameters != null)
            {
                foreach (var pp in api.PathParameters)
                {
                    var pt = ResolveType(pp.Value);
                    var isRef = IsReferenceType(pp.Value);
                    parameters.Add($"{pt}{(isRef ? "?" : "")} {pp.Key}");
                }
            }
            if (api.QueryParameters != null && api.QueryParameters.Count > 0)
            {
                foreach (var qp in api.QueryParameters)
                    parameters.Add($"{ResolveType(qp.Value)}? {qp.Key} = null");
            }
            if (hasBody)
                parameters.Add($"{reqType}? body = null");
            parameters.Add("CancellationToken ct = default");

            // XML documentation
            if (!string.IsNullOrEmpty(api.Description))
                sb.AppendLine($"        /// <summary>{api.Description}</summary>");

            // Parameters
            if (api.PathParameters != null)
                foreach (var pp in api.PathParameters)
                    sb.AppendLine($"        /// <param name=\"{pp.Key}\">{GetParamDescription(pp.Key)}</param>");
            if (api.QueryParameters != null)
                foreach (var qp in api.QueryParameters)
                    sb.AppendLine($"        /// <param name=\"{qp.Key}\">{GetParamDescription(qp.Key)}</param>");
            if (hasBody)
                sb.AppendLine($"        /// <param name=\"body\">请求�?/param>");
            sb.AppendLine($"        /// <param name=\"ct\">取消令牌</param>");

            // Returns
            var returnsDesc = resType != null ? $"API 响应，包含 {api.Id} 的返回数据" : "无返回值";
            sb.AppendLine($"        /// <returns>{returnsDesc}</returns>");

            sb.AppendLine($"        public static async {returnType} {methodName}(");
            sb.AppendLine($"            {string.Join(",\n            ", parameters)})");
            sb.AppendLine($"        {{");

            sb.AppendLine($"            var url = $\"{api.Path}\";");

            if (api.QueryParameters != null && api.QueryParameters.Count > 0)
            {
                sb.AppendLine();
                sb.AppendLine($"            var qp = new Dictionary<string, string?>();");
                foreach (var qp in api.QueryParameters)
                {
                    var t = ResolveType(qp.Value);
                    var isEnum = enumTypeNames.Contains(t);
                    var ns = t != "string" && !isEnum;
                    if (isEnum)
                        sb.AppendLine($"            if ({qp.Key} != null) qp[\"{qp.Key}\"] = ((int){qp.Key}).ToString();");
                    else
                        sb.AppendLine($"            if ({qp.Key} != null) qp[\"{qp.Key}\"] = {qp.Key}{(ns ? "?.ToString()" : "")};");
                }
                sb.AppendLine($"            url += BuildQuery(qp);");
            }

            sb.AppendLine();

            if (resType != null)
            {
                if (method == "GET")
                    sb.AppendLine($"            return await GetAsync<{resType}>(url, ct);");
                else if (method == "POST" && hasBody)
                    sb.AppendLine($"            return await PostAsync<{reqType}, {resType}>(url, body!, ct);");
                else if (method == "PUT" && hasBody)
                    sb.AppendLine($"            return await PutAsync<{reqType}, {resType}>(url, body!, ct);");
                else if (method == "DELETE")
                    sb.AppendLine($"            return await DeleteAsync<{resType}>(url, ct);");
                else if (method == "PATCH" && hasBody)
                    sb.AppendLine($"            return await PatchAsync<{reqType}, {resType}>(url, body!, ct);");
                else
                    sb.AppendLine($"            throw new NotSupportedException();");
            }
            else
            {
                if (method == "POST" && hasBody)
                    sb.AppendLine($"            await PostVoidAsync<{reqType}>(url, body!, ct);");
                else if (method == "PUT" && hasBody)
                    sb.AppendLine($"            await PutVoidAsync<{reqType}>(url, body!, ct);");
                else if (method == "DELETE")
                    sb.AppendLine($"            await DeleteVoidAsync(url, ct);");
                else
                    sb.AppendLine($"            throw new NotSupportedException();");
            }

            sb.AppendLine($"        }}");
            sb.AppendLine();
        }

        private void GenerateTypeWithNested(StringBuilder sb, TypeDefinition type, HashSet<string> allTypes, string indent)
        {
            if (type.NestedTypes != null)
                foreach (var nested in type.NestedTypes.Values)
                    GenerateTypeWithNested(sb, nested, allTypes, indent);
            GenerateType(sb, type, allTypes, indent);
        }

        private void GenerateType(StringBuilder sb, TypeDefinition type, HashSet<string> allTypes, string indent)
        {
            var typeName = type.Type;
            if (string.IsNullOrEmpty(typeName) || !allTypes.Add(typeName)) return;

            var hasCodeMsg = type.Properties.ContainsKey("code") && type.Properties.ContainsKey("msg");
            var baseTypes = hasCodeMsg ? " : IApiResponse" : "";
            sb.AppendLine($"{indent}public class {typeName}{baseTypes}");
            sb.AppendLine($"{indent}{{");
            foreach (var prop in type.Properties)
            {
                var jsonName = prop.Key;
                var propName = ToPascalCase(jsonName);
                var propType = ResolveType(prop.Value.Type);
                var isRef = IsReferenceType(prop.Value.Type);
                var nullable = prop.Value.Nullable || isRef;
                var jsonAttrName = prop.Value.JsonName ?? jsonName;
                sb.AppendLine($"{indent}    [Newtonsoft.Json.JsonProperty(\"{jsonAttrName}\")]");
                sb.AppendLine($"{indent}    public {propType}{(nullable ? "?" : "")} {propName} {{ get; set; }}");
            }
            sb.AppendLine($"{indent}}}");
            sb.AppendLine();
        }

        private static string ToPascalCase(string name)
        {
            if (string.IsNullOrEmpty(name)) return name;
            return char.ToUpperInvariant(name[0]) + name.Substring(1);
        }

        private static string GetParamDescription(string paramName) => paramName switch
        {
            "roleId" => "玩家角色ID（小程序 roleId）",
            "seasonId" => "赛季ID，通过 QuerySeasons 接口获取",
            "gameMode" => "游戏模式ID，见 GameMode 枚举定义",
            "battleId" => "对局ID，通过 GetRecentBattles 接口获取",
            "name" => "搜索关键词（玩家昵称或角色ID）",
            _ => $"参数 {paramName}"
        };

        private static string ResolveType(string type) => type switch
        {
            "string" => "string", "int" => "int", "long" => "long",
            "float" => "float", "double" => "double", "bool" => "bool",
            "decimal" => "decimal", "DateTime" => "System.DateTime",
            "Guid" => "System.Guid", _ => type
        };

        private static bool IsReferenceType(string type)
        {
            if (type == "string" || type.StartsWith("List<") || type.StartsWith("Dictionary<")) return true;
            if (type == "int" || type == "long" || type == "float" || type == "double" ||
                type == "bool" || type == "decimal" || type == "System.DateTime" ||
                type == "System.Guid" || type == "DateTime" || type == "Guid") return false;
            return true;
        }

        private class ApiDefinitionsRoot
        {
            public string BaseUrl { get; set; } = string.Empty;
            public Dictionary<string, string> DefaultHeaders { get; set; } = new();
            public List<string> EnumTypeNames { get; set; } = new();
            public List<ApiEndpointDefinition> Apis { get; set; } = new();
        }

        private class ApiEndpointDefinition
        {
            public string Id { get; set; } = string.Empty;
            public string Description { get; set; } = string.Empty;
            public string Method { get; set; } = "GET";
            public string Path { get; set; } = string.Empty;
            public Dictionary<string, string> PathParameters { get; set; } = new();
            public Dictionary<string, string> QueryParameters { get; set; } = new();
            public Dictionary<string, string> Headers { get; set; } = new();
            public TypeDefinition? RequestBody { get; set; }
            public TypeDefinition? ResponseBody { get; set; }
        }

        private class TypeDefinition
        {
            public string Type { get; set; } = string.Empty;
            public Dictionary<string, PropertyDefinition> Properties { get; set; } = new();
            public Dictionary<string, TypeDefinition> NestedTypes { get; set; } = new();
        }

        private class PropertyDefinition
        {
            public string Type { get; set; } = "string";
            public bool Nullable { get; set; }
            public string? JsonName { get; set; }
        }
    }
}
