using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

namespace BlackGoldAncientSword.Framework.SourceGenerator
{
    /// <summary>
    /// 基于 api-definitions.json 生成 HTTP DTO 与静态客户端 NarakaApiClient。
    /// 仅在 MSBuild 属性 BgaSourceGenMode 为 "Client"（默认）时生成。
    /// </summary>
    [Generator]
    internal class HttpApiSourceGenerator : IIncrementalGenerator
    {
        private const string ModeClient = "Client";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // 读取 RootNamespace
            var rootNsProvider = context.AnalyzerConfigOptionsProvider
                .Select(static (options, _) =>
                    options.GlobalOptions.TryGetValue("build_property.RootNamespace", out var ns)
                        ? ns
                        : "RootNamespace");

            // 读取 BgaSourceGenMode（默认 Client）
            var modeProvider = context.AnalyzerConfigOptionsProvider
                .Select(static (options, _) =>
                    options.GlobalOptions.TryGetValue("build_property.BgaSourceGenMode", out var mode) && !string.IsNullOrWhiteSpace(mode)
                        ? mode
                        : ModeClient);

            var jsonFiles = context.AdditionalTextsProvider
                .Where(static file =>
                    file.Path.EndsWith(".json", StringComparison.OrdinalIgnoreCase) &&
                    file.Path.Contains("Definitions"))
                .Select(static (file, ct) =>
                {
                    var sourceText = file.GetText(ct);
                    return sourceText?.ToString() ?? string.Empty;
                })
                .Where(static text => !string.IsNullOrWhiteSpace(text));

            var combined = jsonFiles.Combine(rootNsProvider).Combine(modeProvider);

            context.RegisterSourceOutput(combined, GenerateAllSources);
        }

        private void GenerateAllSources(SourceProductionContext context, ((string json, string rootNs) inner, string mode) input)
        {
            var (json, rootNs) = input.inner;
            var mode = input.mode;

            // 仅在 Client 模式下生成 DTO/Client；Tests 模式跳过避免与 Framework 重复定义
            if (!string.Equals(mode, ModeClient, StringComparison.OrdinalIgnoreCase))
                return;

            var httpNs = $"{rootNs}.Http";
            var generatedNs = $"{httpNs}.Generated";

            try
            {
                var root = ApiDefinitionsParser.Parse(json);
                if (root == null || root.Apis.Count == 0) return;

                GenerateDtos(context, root, generatedNs);
                GenerateStaticClient(context, root, httpNs, generatedNs);
            }
            catch (Exception ex)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor("HTTPGEN001", "HTTP API Generator Error",
                        $"Failed to generate HTTP API code: {ex.Message}",
                        "HttpApiSourceGenerator", DiagnosticSeverity.Error, isEnabledByDefault: true),
                    Location.None));
            }
        }

        // ==================== DTOs ====================

        private void GenerateDtos(SourceProductionContext context, ApiDefinitionsRoot root, string ns)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>API response interface for extracting error messages</summary>");
            sb.AppendLine("    public interface IApiResponse");
            sb.AppendLine("    {");
            sb.AppendLine("        double? Code { get; }");
            sb.AppendLine("        string? Msg { get; }");
            sb.AppendLine("    }");
            sb.AppendLine();

            var allTypes = new HashSet<string>();
            foreach (var api in root.Apis)
            {
                if (api.RequestBody != null)
                    GenerateType(sb, api.RequestBody, allTypes, "    ");
                if (api.ResponseBody != null)
                    GenerateTypeWithNested(sb, api.ResponseBody, allTypes, "    ");
            }

            sb.AppendLine("}");
            context.AddSource("HttpDtos.Generated.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        // ==================== Static Client ====================

        private void GenerateStaticClient(SourceProductionContext context, ApiDefinitionsRoot root, string httpNs, string generatedNs)
        {
            var sb = new StringBuilder();
            var enumTypeNames = new HashSet<string>(root.EnumTypeNames ?? new List<string>());

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using System.Net.Http;");
            sb.AppendLine("using System.Net.Http.Json;");
            sb.AppendLine("using System.Text;");
            sb.AppendLine("using System.Text.Json;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine($"using {generatedNs};");
            if (enumTypeNames.Count > 0)
                sb.AppendLine("using BlackGoldAncientSword.Framework.Core.Consts;");
            sb.AppendLine();
            sb.AppendLine($"namespace {httpNs}");
            sb.AppendLine("{");
            sb.AppendLine("    public static class NarakaApiClient");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 全局 JSON 序列化选项（与 Newtonsoft 默认宽松行为对齐）：");
            sb.AppendLine("        /// - PropertyNameCaseInsensitive：忽略字段名大小写差异");
            sb.AppendLine("        /// - NumberHandling.AllowReadingFromString：兼容后端把数字写成字符串的响应（如 \"code\": \"200\"）");
            sb.AppendLine("        /// - JsonFlexibleStringConverter：兼容后端 string 字段返回 number/bool（如 stats[].value 既可能是 247 也可能是 \"4.9%\"）");
            sb.AppendLine("        /// - DTO 已通过 [JsonPropertyName] 显式标注 camelCase，无需设置全局 PropertyNamingPolicy");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static readonly JsonSerializerOptions JsonOptions = new()");
            sb.AppendLine("        {");
            sb.AppendLine("            PropertyNameCaseInsensitive = true,");
            sb.AppendLine("            ReadCommentHandling = JsonCommentHandling.Skip,");
            sb.AppendLine("            AllowTrailingCommas = true,");
            sb.AppendLine("            NumberHandling = System.Text.Json.Serialization.JsonNumberHandling.AllowReadingFromString,");
            sb.AppendLine("            Converters = { new JsonFlexibleStringConverter() }");
            sb.AppendLine("        };");
            sb.AppendLine();
            sb.AppendLine($"        private static readonly Uri _baseAddress = new(\"{root.BaseUrl}\");");
            sb.AppendLine();
            sb.AppendLine("        private static HttpClient _http = CreateDefaultClient();");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 暴露内部 HttpClient 给需要手写调用非 code-gen 路径的 auth 场景（滑块验证 / 微信扫码 / refresh 等）。");
            sb.AppendLine("        /// 与生成的方法共享同一条 handler 链（Signature + AuthToken），所以调用时会自动签名 + 加 Bearer。");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static HttpClient Http => _http;");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 注入自定义 <see cref=\"HttpMessageHandler\"/>（例如 SignatureHandler + AuthTokenHandler 链）。");
            sb.AppendLine("        /// App 启动装配阶段调用一次；调用后旧的 HttpClient 会被释放。");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static void Configure(HttpMessageHandler handler)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (handler is null) throw new ArgumentNullException(nameof(handler));");
            sb.AppendLine("            var oldClient = System.Threading.Interlocked.Exchange(ref _http, BuildClient(handler));");
            sb.AppendLine("            oldClient?.Dispose();");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static HttpClient CreateDefaultClient()");
            sb.AppendLine("        {");
            sb.AppendLine("            return BuildClient(new HttpClientHandler());");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static HttpClient BuildClient(HttpMessageHandler handler)");
            sb.AppendLine("        {");
            sb.AppendLine("            var client = new HttpClient(handler) { BaseAddress = _baseAddress };");
            foreach (var h in root.DefaultHeaders)
                sb.AppendLine($"            client.DefaultRequestHeaders.TryAddWithoutValidation(\"{h.Key}\", \"{h.Value}\");");
            sb.AppendLine("            return client;");
            sb.AppendLine("        }");
            sb.AppendLine();

            foreach (var api in root.Apis)
                GenerateApiMethod(sb, api, enumTypeNames);

            sb.AppendLine("        #region Internal");
            sb.AppendLine();
            sb.AppendLine("        private static async Task<T> GetAsync<T>(string url, CancellationToken ct)");
            sb.AppendLine("        {");
            sb.AppendLine("            var r = await _http.GetAsync(url, ct).ConfigureAwait(false);");
            sb.AppendLine("            return await ReadApiResponseAsync<T>(r, ct).ConfigureAwait(false);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static async Task<TRes> PostAsync<TReq, TRes>(string url, TReq body, CancellationToken ct)");
            sb.AppendLine("        {");
            sb.AppendLine("            var r = await _http.PostAsJsonAsync(url, body, JsonOptions, ct).ConfigureAwait(false);");
            sb.AppendLine("            return await ReadApiResponseAsync<TRes>(r, ct).ConfigureAwait(false);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static async Task PostVoidAsync<TReq>(string url, TReq body, CancellationToken ct)");
            sb.AppendLine("        {");
            sb.AppendLine("            var r = await _http.PostAsJsonAsync(url, body, JsonOptions, ct).ConfigureAwait(false);");
            sb.AppendLine("            r.EnsureSuccessStatusCode();");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static async Task<TRes> PutAsync<TReq, TRes>(string url, TReq body, CancellationToken ct)");
            sb.AppendLine("        {");
            sb.AppendLine("            var r = await _http.PutAsJsonAsync(url, body, JsonOptions, ct).ConfigureAwait(false);");
            sb.AppendLine("            return await ReadApiResponseAsync<TRes>(r, ct).ConfigureAwait(false);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static async Task PutVoidAsync<TReq>(string url, TReq body, CancellationToken ct)");
            sb.AppendLine("        {");
            sb.AppendLine("            var r = await _http.PutAsJsonAsync(url, body, JsonOptions, ct).ConfigureAwait(false);");
            sb.AppendLine("            r.EnsureSuccessStatusCode();");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static async Task<T> DeleteAsync<T>(string url, CancellationToken ct)");
            sb.AppendLine("        {");
            sb.AppendLine("            var r = await _http.DeleteAsync(url, ct).ConfigureAwait(false);");
            sb.AppendLine("            return await ReadApiResponseAsync<T>(r, ct).ConfigureAwait(false);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static async Task DeleteVoidAsync(string url, CancellationToken ct)");
            sb.AppendLine("        {");
            sb.AppendLine("            var r = await _http.DeleteAsync(url, ct).ConfigureAwait(false);");
            sb.AppendLine("            r.EnsureSuccessStatusCode();");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static async Task<TRes> PatchAsync<TReq, TRes>(string url, TReq body, CancellationToken ct)");
            sb.AppendLine("        {");
            sb.AppendLine("            var c = new StringContent(JsonSerializer.Serialize(body, JsonOptions), Encoding.UTF8, \"application/json\");");
            sb.AppendLine("            var r = await _http.PatchAsync(url, c, ct).ConfigureAwait(false);");
            sb.AppendLine("            return await ReadApiResponseAsync<TRes>(r, ct).ConfigureAwait(false);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static async Task<T> ReadApiResponseAsync<T>(HttpResponseMessage r, CancellationToken ct)");
            sb.AppendLine("        {");
            sb.AppendLine("            var body = await r.Content.ReadAsStringAsync(ct).ConfigureAwait(false);");
            sb.AppendLine("            if (!r.IsSuccessStatusCode)");
            sb.AppendLine("            {");
            sb.AppendLine("                var apiMsg = TryExtractApiError(body);");
            sb.AppendLine("                throw new HttpRequestException(apiMsg ?? $\"HTTP {(int)r.StatusCode}: {body}\");");
            sb.AppendLine("            }");
            sb.AppendLine("            var result = JsonSerializer.Deserialize<T>(body, JsonOptions)!;");
            sb.AppendLine("            // 后端历史契约：code=200 表示成功；升级后契约：code=0 表示成功。");
            sb.AppendLine("            // 两套并存期为兼容旧数据/旧网关（如仍返回 200）都放行。");
            sb.AppendLine("            if (result is IApiResponse apiResp && apiResp.Code != 200 && apiResp.Code != 0)");
            sb.AppendLine("                throw new InvalidOperationException(apiResp.Msg ?? $\"API returned code {apiResp.Code}\");");
            sb.AppendLine("            return result;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static string? TryExtractApiError(string body)");
            sb.AppendLine("        {");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine("                using var doc = JsonDocument.Parse(body);");
            sb.AppendLine("                if (doc.RootElement.ValueKind == JsonValueKind.Object &&");
            sb.AppendLine("                    doc.RootElement.TryGetProperty(\"msg\", out var msgEl) &&");
            sb.AppendLine("                    msgEl.ValueKind == JsonValueKind.String)");
            sb.AppendLine("                {");
            sb.AppendLine("                    var msg = msgEl.GetString();");
            sb.AppendLine("                    return !string.IsNullOrEmpty(msg) ? msg : null;");
            sb.AppendLine("                }");
            sb.AppendLine("                return null;");
            sb.AppendLine("            }");
            sb.AppendLine("            catch { return null; }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static string BuildQuery(Dictionary<string, string?> p)");
            sb.AppendLine("        {");
            sb.AppendLine("            var q = string.Join(\"&\", p.Where(x => x.Value != null)");
            sb.AppendLine("                .Select(x => $\"{Uri.EscapeDataString(x.Key)}={Uri.EscapeDataString(x.Value!)}\"));");
            sb.AppendLine("            return string.IsNullOrEmpty(q) ? \"\" : \"?\" + q;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        #endregion");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource("NarakaApiClient.Generated.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private void GenerateApiMethod(StringBuilder sb, ApiEndpointDefinition api, HashSet<string> enumTypeNames)
        {
            var methodName = $"{api.Id}Async";
            var method = api.Method.ToUpperInvariant();
            var hasBody = api.RequestBody != null;
            var reqType = hasBody ? $"{api.RequestBody!.Type}" : null;
            var resType = api.ResponseBody != null ? $"{api.ResponseBody!.Type}" : null;
            var returnType = resType != null ? $"Task<{resType}>" : "Task";

            var parameters = new List<string>();
            if (api.PathParameters != null)
            {
                foreach (var pp in api.PathParameters)
                {
                    var pt = ApiDefinitionsParser.ResolveType(pp.Value);
                    var isRef = ApiDefinitionsParser.IsReferenceType(pp.Value);
                    parameters.Add($"{pt}{(isRef ? "?" : "")} {pp.Key}");
                }
            }
            if (api.QueryParameters != null && api.QueryParameters.Count > 0)
            {
                foreach (var qp in api.QueryParameters)
                    parameters.Add($"{ApiDefinitionsParser.ResolveType(qp.Value)}? {qp.Key} = null");
            }
            if (hasBody)
                parameters.Add($"{reqType}? body = null");
            parameters.Add("CancellationToken ct = default");

            // XML documentation
            if (!string.IsNullOrEmpty(api.Description))
                sb.AppendLine($"        /// <summary>{api.Description}</summary>");

            // Parameters
            if (api.PathParameters != null)
                foreach (var pp in api.PathParameters)
                    sb.AppendLine($"        /// <param name=\"{pp.Key}\">{ApiDefinitionsParser.GetParamDescription(pp.Key)}</param>");
            if (api.QueryParameters != null)
                foreach (var qp in api.QueryParameters)
                    sb.AppendLine($"        /// <param name=\"{qp.Key}\">{ApiDefinitionsParser.GetParamDescription(qp.Key)}</param>");
            if (hasBody)
                sb.AppendLine($"        /// <param name=\"body\">请求体</param>");
            sb.AppendLine($"        /// <param name=\"ct\">取消令牌</param>");

            // Returns
            var returnsDesc = resType != null ? $"API 响应，包含 {api.Id} 的返回数据" : "无返回值";
            sb.AppendLine($"        /// <returns>{returnsDesc}</returns>");

            sb.AppendLine($"        public static async {returnType} {methodName}(");
            sb.AppendLine($"            {string.Join(",\n            ", parameters)})");
            sb.AppendLine($"        {{");

            sb.AppendLine($"            var url = $\"{api.Path}\";");

            if (api.QueryParameters != null && api.QueryParameters.Count > 0)
            {
                sb.AppendLine();
                sb.AppendLine($"            var qp = new Dictionary<string, string?>();");
                foreach (var qp in api.QueryParameters)
                {
                    var t = ApiDefinitionsParser.ResolveType(qp.Value);
                    var isEnum = enumTypeNames.Contains(t);
                    var ns = t != "string" && !isEnum;
                    if (isEnum)
                        sb.AppendLine($"            if ({qp.Key} != null) qp[\"{qp.Key}\"] = ((int){qp.Key}).ToString();");
                    else
                        sb.AppendLine($"            if ({qp.Key} != null) qp[\"{qp.Key}\"] = {qp.Key}{(ns ? "?.ToString()" : "")};");
                }
                sb.AppendLine($"            url += BuildQuery(qp);");
            }

            sb.AppendLine();

            if (resType != null)
            {
                if (method == "GET")
                    sb.AppendLine($"            return await GetAsync<{resType}>(url, ct);");
                else if (method == "POST" && hasBody)
                    sb.AppendLine($"            return await PostAsync<{reqType}, {resType}>(url, body!, ct);");
                else if (method == "PUT" && hasBody)
                    sb.AppendLine($"            return await PutAsync<{reqType}, {resType}>(url, body!, ct);");
                else if (method == "DELETE")
                    sb.AppendLine($"            return await DeleteAsync<{resType}>(url, ct);");
                else if (method == "PATCH" && hasBody)
                    sb.AppendLine($"            return await PatchAsync<{reqType}, {resType}>(url, body!, ct);");
                else
                    sb.AppendLine($"            throw new NotSupportedException();");
            }
            else
            {
                if (method == "POST" && hasBody)
                    sb.AppendLine($"            await PostVoidAsync<{reqType}>(url, body!, ct);");
                else if (method == "PUT" && hasBody)
                    sb.AppendLine($"            await PutVoidAsync<{reqType}>(url, body!, ct);");
                else if (method == "DELETE")
                    sb.AppendLine($"            await DeleteVoidAsync(url, ct);");
                else
                    sb.AppendLine($"            throw new NotSupportedException();");
            }

            sb.AppendLine($"        }}");
            sb.AppendLine();
        }

        private void GenerateTypeWithNested(StringBuilder sb, TypeDefinition type, HashSet<string> allTypes, string indent)
        {
            if (type.NestedTypes != null)
                foreach (var nested in type.NestedTypes.Values)
                    GenerateTypeWithNested(sb, nested, allTypes, indent);
            GenerateType(sb, type, allTypes, indent);
        }

        private void GenerateType(StringBuilder sb, TypeDefinition type, HashSet<string> allTypes, string indent)
        {
            var typeName = type.Type;
            if (string.IsNullOrEmpty(typeName) || !allTypes.Add(typeName)) return;

            var hasCodeMsg = type.Properties.ContainsKey("code") && type.Properties.ContainsKey("msg");
            var baseTypes = hasCodeMsg ? " : IApiResponse" : "";
            sb.AppendLine($"{indent}public class {typeName}{baseTypes}");
            sb.AppendLine($"{indent}{{");
            foreach (var prop in type.Properties)
            {
                var jsonName = prop.Key;
                var propName = ApiDefinitionsParser.ToPascalCase(jsonName);
                var propType = ApiDefinitionsParser.ResolveType(prop.Value.Type);
                var isRef = ApiDefinitionsParser.IsReferenceType(prop.Value.Type);
                var nullable = isRef || prop.Value.Nullable != false;
                var jsonAttrName = prop.Value.JsonName ?? jsonName;
                sb.AppendLine($"{indent}    [System.Text.Json.Serialization.JsonPropertyName(\"{jsonAttrName}\")]");
                sb.AppendLine($"{indent}    public {propType}{(nullable ? "?" : "")} {propName} {{ get; set; }}");
            }
            sb.AppendLine($"{indent}}}");
            sb.AppendLine();
        }
    }
}
