using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

namespace BlackGoldAncientSword.Framework.SourceGenerator
{

    [Generator]
    internal class HttpApiSourceGenerator : IIncrementalGenerator
    {
        private const string ModeClient = "Client";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var rootNsProvider = context.AnalyzerConfigOptionsProvider
                .Select(static (options, _) =>
                    options.GlobalOptions.TryGetValue("build_property.RootNamespace", out var ns)
                        ? ns
                        : "RootNamespace");

            var modeProvider = context.AnalyzerConfigOptionsProvider
                .Select(static (options, _) =>
                    options.GlobalOptions.TryGetValue("build_property.BgaSourceGenMode", out var mode) && !string.IsNullOrWhiteSpace(mode)
                        ? mode
                        : ModeClient);

            var jsonFiles = context.AdditionalTextsProvider
                .Where(static file =>
                    file.Path.EndsWith(".json", StringComparison.OrdinalIgnoreCase) &&
                    file.Path.Contains("Definitions"))
                .Select(static (file, ct) =>
                {
                    var sourceText = file.GetText(ct);
                    return sourceText?.ToString() ?? string.Empty;
                })
                .Where(static text => !string.IsNullOrWhiteSpace(text));

            var combined = jsonFiles.Combine(rootNsProvider).Combine(modeProvider);

            context.RegisterSourceOutput(combined, GenerateAllSources);
        }

        private void GenerateAllSources(SourceProductionContext context, ((string json, string rootNs) inner, string mode) input)
        {
            var (json, rootNs) = input.inner;
            var mode = input.mode;

            if (!string.Equals(mode, ModeClient, StringComparison.OrdinalIgnoreCase))
                return;

            var httpNs = $"{rootNs}.Http";
            var generatedNs = $"{httpNs}.Generated";

            try
            {
                var root = ApiDefinitionsParser.Parse(json);
                if (root == null || root.Apis.Count == 0) return;

                GenerateDtos(context, root, generatedNs);
                GenerateStaticClient(context, root, httpNs, generatedNs);
            }
            catch (Exception ex)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor("HTTPGEN001", "HTTP API Generator Error",
                        $"Failed to generate HTTP API code: {ex.Message}",
                        "HttpApiSourceGenerator", DiagnosticSeverity.Error, isEnabledByDefault: true),
                    Location.None));
            }
        }

        private void GenerateDtos(SourceProductionContext context, ApiDefinitionsRoot root, string ns)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            sb.AppendLine("    public interface IApiResponse");
            sb.AppendLine("    {");
            sb.AppendLine("        bool IsSuccess { get; }");
            sb.AppendLine("        string? Msg { get; }");
            sb.AppendLine("    }");
            sb.AppendLine();

            var allTypes = new HashSet<string>();
            foreach (var api in root.Apis)
            {
                if (api.RequestBody != null)
                    GenerateType(sb, api.RequestBody, allTypes, "    ", root.Envelope);
                if (api.ResponseBody != null)
                    GenerateTypeWithNested(sb, api.ResponseBody, allTypes, "    ", root.Envelope);
            }

            sb.AppendLine("}");
            context.AddSource("HttpDtos.Generated.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private void GenerateStaticClient(SourceProductionContext context, ApiDefinitionsRoot root, string httpNs, string generatedNs)
        {
            var sb = new StringBuilder();
            var enumTypeNames = new HashSet<string>(root.EnumTypeNames ?? new List<string>());

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using System.Net.Http;");
            sb.AppendLine("using System.Net.Http.Json;");
            sb.AppendLine("using System.Text;");
            sb.AppendLine("using System.Text.Json;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine($"using {generatedNs};");
            if (enumTypeNames.Count > 0)
                sb.AppendLine("using BlackGoldAncientSword.Framework.Core.Consts;");
            sb.AppendLine();
            sb.AppendLine($"namespace {httpNs}");
            sb.AppendLine("{");
            sb.AppendLine("    public static class NarakaApiClient");
            sb.AppendLine("    {");
            sb.AppendLine("        public static readonly JsonSerializerOptions JsonOptions = new()");
            sb.AppendLine("        {");
            sb.AppendLine("            PropertyNameCaseInsensitive = true,");
            sb.AppendLine("            ReadCommentHandling = JsonCommentHandling.Skip,");
            sb.AppendLine("            AllowTrailingCommas = true,");
            sb.AppendLine("            NumberHandling = System.Text.Json.Serialization.JsonNumberHandling.AllowReadingFromString,");
            sb.AppendLine("            Converters = { new JsonFlexibleStringConverter() }");
            sb.AppendLine("        };");
            sb.AppendLine();
            sb.AppendLine($"        private static readonly Uri _baseAddress = new(\"{root.BaseUrl}\");");
            sb.AppendLine();
            sb.AppendLine("        private static HttpClient _http = CreateDefaultClient();");
            sb.AppendLine();
            sb.AppendLine("        public static HttpClient Http => _http;");
            sb.AppendLine();
            sb.AppendLine("        public static void Configure(HttpMessageHandler handler)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (handler is null) throw new ArgumentNullException(nameof(handler));");
            sb.AppendLine("            var oldClient = System.Threading.Interlocked.Exchange(ref _http, BuildClient(handler));");
            sb.AppendLine("            oldClient?.Dispose();");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static HttpClient CreateDefaultClient()");
            sb.AppendLine("        {");
            sb.AppendLine("            return BuildClient(new HttpClientHandler());");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static HttpClient BuildClient(HttpMessageHandler handler)");
            sb.AppendLine("        {");
            sb.AppendLine("            var client = new HttpClient(handler) { BaseAddress = _baseAddress };");
            foreach (var h in root.DefaultHeaders)
                sb.AppendLine($"            client.DefaultRequestHeaders.TryAddWithoutValidation(\"{h.Key}\", \"{h.Value}\");");
            sb.AppendLine("            return client;");
            sb.AppendLine("        }");
            sb.AppendLine();

            foreach (var api in root.Apis)
                GenerateApiMethod(sb, api, enumTypeNames);

            sb.AppendLine("        #region Internal");
            sb.AppendLine();
            sb.AppendLine("        private static async Task<T> GetAsync<T>(string url, CancellationToken ct)");
            sb.AppendLine("        {");
            sb.AppendLine("            var r = await _http.GetAsync(url, ct).ConfigureAwait(false);");
            sb.AppendLine("            return await ReadApiResponseAsync<T>(r, ct).ConfigureAwait(false);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static async Task<TRes> PostAsync<TReq, TRes>(string url, TReq body, CancellationToken ct)");
            sb.AppendLine("        {");
            sb.AppendLine("            var r = await _http.PostAsJsonAsync(url, body, JsonOptions, ct).ConfigureAwait(false);");
            sb.AppendLine("            return await ReadApiResponseAsync<TRes>(r, ct).ConfigureAwait(false);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static async Task PostVoidAsync<TReq>(string url, TReq body, CancellationToken ct)");
            sb.AppendLine("        {");
            sb.AppendLine("            var r = await _http.PostAsJsonAsync(url, body, JsonOptions, ct).ConfigureAwait(false);");
            sb.AppendLine("            r.EnsureSuccessStatusCode();");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static async Task<TRes> PutAsync<TReq, TRes>(string url, TReq body, CancellationToken ct)");
            sb.AppendLine("        {");
            sb.AppendLine("            var r = await _http.PutAsJsonAsync(url, body, JsonOptions, ct).ConfigureAwait(false);");
            sb.AppendLine("            return await ReadApiResponseAsync<TRes>(r, ct).ConfigureAwait(false);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static async Task PutVoidAsync<TReq>(string url, TReq body, CancellationToken ct)");
            sb.AppendLine("        {");
            sb.AppendLine("            var r = await _http.PutAsJsonAsync(url, body, JsonOptions, ct).ConfigureAwait(false);");
            sb.AppendLine("            r.EnsureSuccessStatusCode();");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static async Task<T> DeleteAsync<T>(string url, CancellationToken ct)");
            sb.AppendLine("        {");
            sb.AppendLine("            var r = await _http.DeleteAsync(url, ct).ConfigureAwait(false);");
            sb.AppendLine("            return await ReadApiResponseAsync<T>(r, ct).ConfigureAwait(false);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static async Task DeleteVoidAsync(string url, CancellationToken ct)");
            sb.AppendLine("        {");
            sb.AppendLine("            var r = await _http.DeleteAsync(url, ct).ConfigureAwait(false);");
            sb.AppendLine("            r.EnsureSuccessStatusCode();");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static async Task<TRes> PatchAsync<TReq, TRes>(string url, TReq body, CancellationToken ct)");
            sb.AppendLine("        {");
            sb.AppendLine("            var c = new StringContent(JsonSerializer.Serialize(body, JsonOptions), Encoding.UTF8, \"application/json\");");
            sb.AppendLine("            var r = await _http.PatchAsync(url, c, ct).ConfigureAwait(false);");
            sb.AppendLine("            return await ReadApiResponseAsync<TRes>(r, ct).ConfigureAwait(false);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static async Task<T> ReadApiResponseAsync<T>(HttpResponseMessage r, CancellationToken ct)");
            sb.AppendLine("        {");
            sb.AppendLine("            var body = await r.Content.ReadAsStringAsync(ct).ConfigureAwait(false);");
            sb.AppendLine("            if (!r.IsSuccessStatusCode)");
            sb.AppendLine("            {");
            sb.AppendLine("                // 上层约定：只展示后端 msg，前端不拼任何兜底文案；msg 为 null 时上层静默。");
            sb.AppendLine("                throw new NarakaApiException(-(int)r.StatusCode, TryExtractApiError(body));");
            sb.AppendLine("            }");
            sb.AppendLine("            var result = JsonSerializer.Deserialize<T>(body, JsonOptions)!;");
            sb.AppendLine("            // 成功口径由信封字段决定（旧后端 code=200/0，小黑盒 status=ok），见 api-definitions.json 的 envelope。");
            sb.AppendLine("            // 业务失败一律用 0 当 code：上层只展示 Msg，不依赖数值码。");
            sb.AppendLine("            if (result is IApiResponse apiResp && !apiResp.IsSuccess)");
            sb.AppendLine("                throw new NarakaApiException(0, apiResp.Msg);");
            sb.AppendLine("            return result;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static string? TryExtractApiError(string body)");
            sb.AppendLine("        {");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine("                using var doc = JsonDocument.Parse(body);");
            sb.AppendLine("                if (doc.RootElement.ValueKind == JsonValueKind.Object &&");
            sb.AppendLine("                    doc.RootElement.TryGetProperty(\"msg\", out var msgEl) &&");
            sb.AppendLine("                    msgEl.ValueKind == JsonValueKind.String)");
            sb.AppendLine("                {");
            sb.AppendLine("                    var msg = msgEl.GetString();");
            sb.AppendLine("                    return !string.IsNullOrEmpty(msg) ? msg : null;");
            sb.AppendLine("                }");
            sb.AppendLine("                return null;");
            sb.AppendLine("            }");
            sb.AppendLine("            catch { return null; }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static string BuildQuery(Dictionary<string, string?> p)");
            sb.AppendLine("        {");
            sb.AppendLine("            var q = string.Join(\"&\", p.Where(x => x.Value != null)");
            sb.AppendLine("                .Select(x => $\"{Uri.EscapeDataString(x.Key)}={Uri.EscapeDataString(x.Value!)}\"));");
            sb.AppendLine("            return string.IsNullOrEmpty(q) ? \"\" : \"?\" + q;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        #endregion");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource("NarakaApiClient.Generated.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private void GenerateApiMethod(StringBuilder sb, ApiEndpointDefinition api, HashSet<string> enumTypeNames)
        {
            var methodName = $"{api.Id}Async";
            var method = api.Method.ToUpperInvariant();
            var hasBody = api.RequestBody != null;
            var reqType = hasBody ? $"{api.RequestBody!.Type}" : null;
            var resType = api.ResponseBody != null ? $"{api.ResponseBody!.Type}" : null;
            var returnType = resType != null ? $"Task<{resType}>" : "Task";

            var parameters = new List<string>();
            if (api.PathParameters != null)
            {
                foreach (var pp in api.PathParameters)
                {
                    var pt = ApiDefinitionsParser.ResolveType(pp.Value);
                    var isRef = ApiDefinitionsParser.IsReferenceType(pp.Value);
                    parameters.Add($"{pt}{(isRef ? "?" : "")} {pp.Key}");
                }
            }
            if (api.QueryParameters != null && api.QueryParameters.Count > 0)
            {
                foreach (var qp in api.QueryParameters)
                    parameters.Add($"{ApiDefinitionsParser.ResolveType(qp.Value)}? {ApiDefinitionsParser.ToCamelCase(qp.Key)} = null");
            }
            if (hasBody)
                parameters.Add($"{reqType}? body = null");
            parameters.Add("CancellationToken ct = default");



            var returnsDesc = resType != null ? $"API 响应，包含 {api.Id} 的返回数据" : "无返回值";

            sb.AppendLine($"        public static async {returnType} {methodName}(");
            sb.AppendLine($"            {string.Join(",\n            ", parameters)})");
            sb.AppendLine($"        {{");

            sb.AppendLine($"            var url = $\"{api.Path}\";");

            if (api.QueryParameters != null && api.QueryParameters.Count > 0)
            {
                sb.AppendLine();
                sb.AppendLine($"            var qp = new Dictionary<string, string?>();");
                foreach (var qp in api.QueryParameters)
                {
                    var t = ApiDefinitionsParser.ResolveType(qp.Value);
                    var isEnum = enumTypeNames.Contains(t);
                    var ns = t != "string" && !isEnum;
                    var arg = ApiDefinitionsParser.ToCamelCase(qp.Key);
                    if (isEnum)
                        sb.AppendLine($"            if ({arg} != null) qp[\"{qp.Key}\"] = ((int){arg}).ToString();");
                    else
                        sb.AppendLine($"            if ({arg} != null) qp[\"{qp.Key}\"] = {arg}{(ns ? "?.ToString()" : "")};");
                }
                sb.AppendLine($"            url += BuildQuery(qp);");
            }

            sb.AppendLine();

            if (resType != null)
            {
                if (method == "GET")
                    sb.AppendLine($"            return await GetAsync<{resType}>(url, ct);");
                else if (method == "POST" && hasBody)
                    sb.AppendLine($"            return await PostAsync<{reqType}, {resType}>(url, body!, ct);");
                else if (method == "PUT" && hasBody)
                    sb.AppendLine($"            return await PutAsync<{reqType}, {resType}>(url, body!, ct);");
                else if (method == "DELETE")
                    sb.AppendLine($"            return await DeleteAsync<{resType}>(url, ct);");
                else if (method == "PATCH" && hasBody)
                    sb.AppendLine($"            return await PatchAsync<{reqType}, {resType}>(url, body!, ct);");
                else
                    sb.AppendLine($"            throw new NotSupportedException();");
            }
            else
            {
                if (method == "POST" && hasBody)
                    sb.AppendLine($"            await PostVoidAsync<{reqType}>(url, body!, ct);");
                else if (method == "PUT" && hasBody)
                    sb.AppendLine($"            await PutVoidAsync<{reqType}>(url, body!, ct);");
                else if (method == "DELETE")
                    sb.AppendLine($"            await DeleteVoidAsync(url, ct);");
                else
                    sb.AppendLine($"            throw new NotSupportedException();");
            }

            sb.AppendLine($"        }}");
            sb.AppendLine();
        }

        private void GenerateTypeWithNested(StringBuilder sb, TypeDefinition type, HashSet<string> allTypes, string indent, ApiEnvelopeDefinition envelope)
        {
            if (type.NestedTypes != null)
                foreach (var nested in type.NestedTypes.Values)
                    GenerateTypeWithNested(sb, nested, allTypes, indent, envelope);
            GenerateType(sb, type, allTypes, indent, envelope);
        }

        private void GenerateType(StringBuilder sb, TypeDefinition type, HashSet<string> allTypes, string indent, ApiEnvelopeDefinition envelope)
        {
            var typeName = type.Type;
            if (string.IsNullOrEmpty(typeName) || !allTypes.Add(typeName)) return;

            var isEnvelope = envelope.IsEnvelope(type);
            var baseTypes = isEnvelope ? " : IApiResponse" : "";
            sb.AppendLine($"{indent}public class {typeName}{baseTypes}");
            sb.AppendLine($"{indent}{{");
            foreach (var prop in type.Properties)
            {
                var jsonName = prop.Key;
                var propName = ApiDefinitionsParser.ToPascalCase(jsonName);
                var propType = ApiDefinitionsParser.ResolveType(prop.Value.Type);
                var isRef = ApiDefinitionsParser.IsReferenceType(prop.Value.Type);
                var nullable = isRef || prop.Value.Nullable != false;
                var jsonAttrName = prop.Value.JsonName ?? jsonName;
                sb.AppendLine($"{indent}    [System.Text.Json.Serialization.JsonPropertyName(\"{jsonAttrName}\")]");
                sb.AppendLine($"{indent}    public {propType}{(nullable ? "?" : "")} {propName} {{ get; set; }}");
            }

            if (isEnvelope)
            {
                sb.AppendLine();
                sb.AppendLine($"{indent}    [System.Text.Json.Serialization.JsonIgnore]");
                sb.AppendLine($"{indent}    public bool IsSuccess => {BuildSuccessExpression(type, envelope)};");
            }

            sb.AppendLine($"{indent}}}");
            sb.AppendLine();
        }

        private static string BuildSuccessExpression(TypeDefinition type, ApiEnvelopeDefinition envelope)
        {
            var propName = ApiDefinitionsParser.ToPascalCase(envelope.SuccessProperty);
            var propType = type.Properties.TryGetValue(envelope.SuccessProperty, out var def)
                ? ApiDefinitionsParser.ResolveType(def.Type)
                : "string";

            var comparisons = envelope.SuccessValues.Select(value =>
            {
                if (propType is "double" or "long" or "float" or "decimal" or "int")
                    return $"{propName} == {value}";

                var escaped = value.Replace("\\", "\\\\").Replace("\"", "\\\"");
                return $"string.Equals({propName}, \"{escaped}\", StringComparison.OrdinalIgnoreCase)";
            });

            return string.Join(" || ", comparisons);
        }
    }
}
