using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace BlackGoldAncientSword.Framework.SourceGenerator
{
    /// <summary>
    /// 基于 api-definitions.json 生成 Tests 项目下的 HTTP API 测试代码。
    /// 仅在 MSBuild 属性 BgaSourceGenMode 为 "Tests" 时生成，避免在 Framework 项目误生成测试。
    /// 与 HttpApiSourceGenerator 共享同一份 api-definitions.json，确保测试与生产代码始终对齐。
    /// </summary>
    [Generator]
    internal class HttpApiTestSourceGenerator : IIncrementalGenerator
    {
        private const string ModeTests = "Tests";
        private const string ModeClient = "Client";

        // Framework 项目命名空间（项目内部约定，硬编码以避免 Tests 项目额外配置）
        private const string FrameworkHttpNs = "BlackGoldAncientSword.Framework.Http";
        private const string FrameworkGeneratedNs = "BlackGoldAncientSword.Framework.Http.Generated";
        private const string FrameworkConstsNs = "BlackGoldAncientSword.Framework.Core.Consts";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var rootNsProvider = context.AnalyzerConfigOptionsProvider
                .Select(static (options, _) =>
                    options.GlobalOptions.TryGetValue("build_property.RootNamespace", out var ns)
                        ? ns
                        : "RootNamespace");

            var modeProvider = context.AnalyzerConfigOptionsProvider
                .Select(static (options, _) =>
                    options.GlobalOptions.TryGetValue("build_property.BgaSourceGenMode", out var mode) && !string.IsNullOrWhiteSpace(mode)
                        ? mode
                        : ModeClient);

            var jsonFiles = context.AdditionalTextsProvider
                .Where(static file =>
                    file.Path.EndsWith(".json", StringComparison.OrdinalIgnoreCase) &&
                    file.Path.Contains("Definitions"))
                .Select(static (file, ct) =>
                {
                    var sourceText = file.GetText(ct);
                    return sourceText?.ToString() ?? string.Empty;
                })
                .Where(static text => !string.IsNullOrWhiteSpace(text));

            var combined = jsonFiles.Combine(rootNsProvider).Combine(modeProvider);
            context.RegisterSourceOutput(combined, GenerateAll);
        }

        private void GenerateAll(SourceProductionContext context, ((string json, string rootNs) inner, string mode) input)
        {
            var (json, rootNs) = input.inner;
            var mode = input.mode;

            // 仅在 Tests 模式下生成测试代码
            if (!string.Equals(mode, ModeTests, StringComparison.OrdinalIgnoreCase))
                return;

            try
            {
                var root = ApiDefinitionsParser.Parse(json);
                if (root == null || root.Apis.Count == 0) return;

                var testNs = $"{rootNs}.Http.Generated";
                GenerateClientTests(context, root, testNs);
                GenerateDtoStructureTests(context, root, testNs);
                GenerateDtoRoundtripTests(context, root, testNs);
            }
            catch (Exception ex)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor("HTTPTESTGEN001", "HTTP API Test Generator Error",
                        $"Failed to generate HTTP API test code: {ex.Message}",
                        "HttpApiTestSourceGenerator", DiagnosticSeverity.Error, isEnabledByDefault: true),
                    Location.None));
            }
        }

        // ==================== Client Tests ====================

        private void GenerateClientTests(SourceProductionContext context, ApiDefinitionsRoot root, string testNs)
        {
            var sb = new StringBuilder();
            var enumTypeNames = new HashSet<string>(root.EnumTypeNames ?? new List<string>());

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using System.Reflection;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine($"using {FrameworkHttpNs};");
            sb.AppendLine($"using {FrameworkGeneratedNs};");
            if (enumTypeNames.Count > 0)
                sb.AppendLine($"using {FrameworkConstsNs};");
            sb.AppendLine("using Xunit;");
            sb.AppendLine();
            sb.AppendLine($"namespace {testNs}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// 自动生成：验证 NarakaApiClient 暴露的静态方法与 api-definitions.json 定义一致。");
            sb.AppendLine("    /// 通过反射断言方法名、参数顺序与类型、返回类型，保护 SourceGenerator 契约不被破坏。");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public class GeneratedApiClientTests");
            sb.AppendLine("    {");
            sb.AppendLine("        private static readonly Type ClientType = typeof(NarakaApiClient);");
            sb.AppendLine();
            sb.AppendLine("        [Fact]");
            sb.AppendLine("        public void NarakaApiClient_Should_Be_Static_Class()");
            sb.AppendLine("        {");
            sb.AppendLine("            Assert.True(ClientType.IsAbstract && ClientType.IsSealed, \"NarakaApiClient 应为 static class\");");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        [Fact]");
            sb.AppendLine("        public void NarakaApiClient_Should_Expose_Shared_JsonOptions()");
            sb.AppendLine("        {");
            sb.AppendLine("            var fi = ClientType.GetField(\"JsonOptions\", BindingFlags.Public | BindingFlags.Static);");
            sb.AppendLine("            Assert.NotNull(fi);");
            sb.AppendLine("            Assert.Equal(typeof(System.Text.Json.JsonSerializerOptions), fi!.FieldType);");
            sb.AppendLine("            var value = fi.GetValue(null) as System.Text.Json.JsonSerializerOptions;");
            sb.AppendLine("            Assert.NotNull(value);");
            sb.AppendLine("            Assert.True(value!.PropertyNameCaseInsensitive, \"JsonOptions.PropertyNameCaseInsensitive 应为 true 以兼容旧后端字段大小写\");");
            sb.AppendLine("        }");
            sb.AppendLine();

            foreach (var api in root.Apis)
                GenerateClientMethodTest(sb, api, enumTypeNames);

            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource("GeneratedApiClientTests.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private void GenerateClientMethodTest(StringBuilder sb, ApiEndpointDefinition api, HashSet<string> enumTypeNames)
        {
            var methodName = $"{api.Id}Async";
            var hasBody = api.RequestBody != null;
            var reqType = hasBody ? api.RequestBody!.Type : null;
            var resType = api.ResponseBody?.Type;

            // 构造 (参数名, typeof 表达式) 列表
            var paramSpecs = new List<(string name, string typeOf)>();
            if (api.PathParameters != null)
            {
                foreach (var pp in api.PathParameters)
                {
                    var isRef = ApiDefinitionsParser.IsReferenceType(pp.Value);
                    paramSpecs.Add((pp.Key, ToTypeOfExpr(pp.Value, isRef, enumTypeNames)));
                }
            }
            if (api.QueryParameters != null)
            {
                foreach (var qp in api.QueryParameters)
                {
                    // queryParameters 在生成代码里恒为 nullable
                    paramSpecs.Add((qp.Key, ToTypeOfExpr(qp.Value, true, enumTypeNames)));
                }
            }
            if (hasBody)
                paramSpecs.Add(("body", $"typeof({reqType})"));
            paramSpecs.Add(("ct", "typeof(CancellationToken)"));

            var returnTypeExpr = resType != null ? $"typeof(Task<{resType}>)" : "typeof(Task)";

            sb.AppendLine("        [Fact]");
            sb.AppendLine($"        public void {api.Id}_Method_Should_Have_Correct_Signature()");
            sb.AppendLine("        {");
            sb.AppendLine($"            var method = ClientType.GetMethod(\"{methodName}\", BindingFlags.Public | BindingFlags.Static);");
            sb.AppendLine($"            Assert.NotNull(method);");
            sb.AppendLine($"            Assert.Equal({returnTypeExpr}, method!.ReturnType);");
            sb.AppendLine($"            var ps = method.GetParameters();");
            // 单参数时使用 Assert.Single 以满足 xUnit2013 风格规范
            if (paramSpecs.Count == 1)
                sb.AppendLine($"            Assert.Single(ps);");
            else
                sb.AppendLine($"            Assert.Equal({paramSpecs.Count}, ps.Length);");
            for (var i = 0; i < paramSpecs.Count; i++)
            {
                var (name, typeOf) = paramSpecs[i];
                sb.AppendLine($"            Assert.Equal(\"{name}\", ps[{i}].Name);");
                sb.AppendLine($"            Assert.Equal({typeOf}, ps[{i}].ParameterType);");
            }
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // ==================== DTO Structure Tests ====================

        private void GenerateDtoStructureTests(SourceProductionContext context, ApiDefinitionsRoot root, string testNs)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using System.Reflection;");
            sb.AppendLine("using System.Text.Json.Serialization;");
            sb.AppendLine($"using {FrameworkGeneratedNs};");
            sb.AppendLine("using Xunit;");
            sb.AppendLine();
            sb.AppendLine($"namespace {testNs}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// 自动生成：验证每个 DTO 类型存在、每个属性使用 [JsonPropertyName] 标注，");
            sb.AppendLine("    /// 且标注的 JSON 字段名与 api-definitions.json 定义严格一致。");
            sb.AppendLine("    /// 这是 Newtonsoft → System.Text.Json 迁移的关键回归保护。");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public class GeneratedApiDtoTests");
            sb.AppendLine("    {");

            var allTypes = new HashSet<string>();
            var collected = new List<TypeDefinition>();
            foreach (var api in root.Apis)
            {
                if (api.RequestBody != null) CollectAllTypes(api.RequestBody, allTypes, collected);
                if (api.ResponseBody != null) CollectAllTypes(api.ResponseBody, allTypes, collected);
            }

            foreach (var type in collected)
                GenerateDtoStructureTest(sb, type);

            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource("GeneratedApiDtoTests.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private void GenerateDtoStructureTest(StringBuilder sb, TypeDefinition type)
        {
            var typeName = type.Type;

            sb.AppendLine("        [Fact]");
            sb.AppendLine($"        public void {typeName}_Should_Have_All_Properties_Annotated()");
            sb.AppendLine("        {");
            sb.AppendLine($"            var t = typeof({typeName});");
            sb.AppendLine($"            Assert.NotNull(t);");
            sb.AppendLine($"            var props = t.GetProperties(BindingFlags.Public | BindingFlags.Instance);");
            sb.AppendLine($"            Assert.Equal({type.Properties.Count}, props.Length);");

            foreach (var prop in type.Properties)
            {
                var jsonName = prop.Value.JsonName ?? prop.Key;
                var propName = ApiDefinitionsParser.ToPascalCase(prop.Key);

                sb.AppendLine($"            var p_{propName} = t.GetProperty(\"{propName}\");");
                sb.AppendLine($"            Assert.NotNull(p_{propName});");
                sb.AppendLine($"            var attr_{propName} = p_{propName}!.GetCustomAttribute<JsonPropertyNameAttribute>();");
                sb.AppendLine($"            Assert.NotNull(attr_{propName});");
                sb.AppendLine($"            Assert.Equal(\"{jsonName}\", attr_{propName}!.Name);");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // ==================== DTO Roundtrip Tests ====================

        private void GenerateDtoRoundtripTests(SourceProductionContext context, ApiDefinitionsRoot root, string testNs)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using System.Reflection;");
            sb.AppendLine("using System.Text.Json;");
            sb.AppendLine($"using {FrameworkHttpNs};");
            sb.AppendLine($"using {FrameworkGeneratedNs};");
            sb.AppendLine("using Xunit;");
            sb.AppendLine();
            sb.AppendLine($"namespace {testNs}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// 自动生成：DTO 序列化往返测试。");
            sb.AppendLine("    /// 对每个 DTO 构造示例实例 → 用 NarakaApiClient.JsonOptions 序列化 → 反序列化 → 再次序列化，");
            sb.AppendLine("    /// 比较两次 JSON 是否一致，捕获 JsonPropertyName 错配、属性 setter 缺失等回归问题。");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public class GeneratedApiDtoRoundtripTests");
            sb.AppendLine("    {");

            var allTypes = new HashSet<string>();
            var collected = new List<TypeDefinition>();
            foreach (var api in root.Apis)
            {
                if (api.RequestBody != null) CollectAllTypes(api.RequestBody, allTypes, collected);
                if (api.ResponseBody != null) CollectAllTypes(api.ResponseBody, allTypes, collected);
            }

            foreach (var type in collected)
            {
                sb.AppendLine("        [Fact]");
                sb.AppendLine($"        public void {type.Type}_Should_Roundtrip_Through_JsonSerializer()");
                sb.AppendLine("        {");
                sb.AppendLine($"            var t = typeof({type.Type});");
                sb.AppendLine($"            var sample = DtoSampleFactory.Create(t);");
                sb.AppendLine($"            Assert.NotNull(sample);");
                sb.AppendLine($"            var opts = NarakaApiClient.JsonOptions;");
                sb.AppendLine($"            var json1 = JsonSerializer.Serialize(sample, t, opts);");
                sb.AppendLine($"            var revived = JsonSerializer.Deserialize(json1, t, opts);");
                sb.AppendLine($"            Assert.NotNull(revived);");
                sb.AppendLine($"            var json2 = JsonSerializer.Serialize(revived, t, opts);");
                sb.AppendLine($"            Assert.Equal(json1, json2);");
                sb.AppendLine("        }");
                sb.AppendLine();
            }

            // DtoSampleFactory 辅助类：基于反射为任意 DTO 生成示例值
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 反射构造 DTO 示例实例。对每个 public 属性按类型填充确定性示例值，避免依赖手写样例。");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        private static class DtoSampleFactory");
            sb.AppendLine("        {");
            sb.AppendLine("            public static object? Create(Type t)");
            sb.AppendLine("            {");
            sb.AppendLine("                var underlying = Nullable.GetUnderlyingType(t) ?? t;");
            sb.AppendLine("                if (underlying == typeof(string)) return \"sample\";");
            sb.AppendLine("                if (underlying == typeof(double)) return 42.0d;");
            sb.AppendLine("                if (underlying == typeof(long)) return 42L;");
            sb.AppendLine("                if (underlying == typeof(int)) return 42;");
            sb.AppendLine("                if (underlying == typeof(float)) return 42.0f;");
            sb.AppendLine("                if (underlying == typeof(bool)) return true;");
            sb.AppendLine("                if (underlying == typeof(decimal)) return 42m;");
            sb.AppendLine("                if (underlying == typeof(DateTime)) return new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc);");
            sb.AppendLine("                if (underlying == typeof(Guid)) return Guid.Empty;");
            sb.AppendLine("                if (underlying.IsEnum)");
            sb.AppendLine("                {");
            sb.AppendLine("                    var values = Enum.GetValues(underlying);");
            sb.AppendLine("                    return values.Length > 0 ? values.GetValue(0) : Activator.CreateInstance(underlying);");
            sb.AppendLine("                }");
            sb.AppendLine("                if (underlying.IsGenericType)");
            sb.AppendLine("                {");
            sb.AppendLine("                    var def = underlying.GetGenericTypeDefinition();");
            sb.AppendLine("                    if (def == typeof(List<>) || def == typeof(IList<>) || def == typeof(IEnumerable<>) || def == typeof(ICollection<>))");
            sb.AppendLine("                    {");
            sb.AppendLine("                        var elemType = underlying.GetGenericArguments()[0];");
            sb.AppendLine("                        var listType = typeof(List<>).MakeGenericType(elemType);");
            sb.AppendLine("                        var list = (IList)Activator.CreateInstance(listType)!;");
            sb.AppendLine("                        var elem = Create(elemType);");
            sb.AppendLine("                        if (elem != null) list.Add(elem);");
            sb.AppendLine("                        return list;");
            sb.AppendLine("                    }");
            sb.AppendLine("                    if (def == typeof(Dictionary<,>))");
            sb.AppendLine("                    {");
            sb.AppendLine("                        return Activator.CreateInstance(underlying);");
            sb.AppendLine("                    }");
            sb.AppendLine("                }");
            sb.AppendLine("                if (underlying.IsClass && !underlying.IsAbstract && underlying.GetConstructor(Type.EmptyTypes) != null)");
            sb.AppendLine("                {");
            sb.AppendLine("                    var instance = Activator.CreateInstance(underlying);");
            sb.AppendLine("                    foreach (var p in underlying.GetProperties(BindingFlags.Public | BindingFlags.Instance))");
            sb.AppendLine("                    {");
            sb.AppendLine("                        if (!p.CanWrite) continue;");
            sb.AppendLine("                        var v = Create(p.PropertyType);");
            sb.AppendLine("                        if (v != null) p.SetValue(instance, v);");
            sb.AppendLine("                    }");
            sb.AppendLine("                    return instance;");
            sb.AppendLine("                }");
            sb.AppendLine("                return null;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");

            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource("GeneratedApiDtoRoundtripTests.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        // ==================== Helpers ====================

        private static void CollectAllTypes(TypeDefinition type, HashSet<string> seen, List<TypeDefinition> ordered)
        {
            if (type.NestedTypes != null)
                foreach (var nested in type.NestedTypes.Values)
                    CollectAllTypes(nested, seen, ordered);
            if (!string.IsNullOrEmpty(type.Type) && seen.Add(type.Type))
                ordered.Add(type);
        }

        /// <summary>
        /// 生成参数类型对应的 typeof(...) 表达式。
        /// - string / List / 自定义类等引用类型：typeof(T)（无论是否 optional，nullable 引用类型在反射里与非 nullable 同一类型）
        /// - 枚举与内置值类型：optional 时 typeof(T?)，否则 typeof(T)
        /// </summary>
        private static string ToTypeOfExpr(string defType, bool isOptional, HashSet<string> enumTypes)
        {
            var resolved = ApiDefinitionsParser.ResolveType(defType);

            if (enumTypes.Contains(resolved))
                return isOptional ? $"typeof({resolved}?)" : $"typeof({resolved})";

            // string / List<> / Dictionary<> / 自定义类
            if (ApiDefinitionsParser.IsReferenceType(defType))
                return $"typeof({resolved})";

            // 内置值类型（double/long/float/bool/decimal/DateTime/Guid）
            return isOptional ? $"typeof({resolved}?)" : $"typeof({resolved})";
        }
    }
}
